export const de = {
  // --- App / Header ---
  app: {
    tagline: 'Solar Nutrition Database & App',
    quote: '„Es kommt nicht darauf an, WAS Du isst, sondern WANN Du es isst." – Nach den Lehren von Adano Ley & Atom Bergstrom.',
    localTime: 'Ortszeit',
    trueSolarTime: 'Wahre Sonnenzeit',
    location: 'Standort',
    setLocation: 'Standort festlegen',
    currentPhase: 'Aktuelle Phase:',
    fullMoonDay: '🌕 Vollmond-Tag: Alle Wuchszonen & Kombinationen erlaubt!',
    lunarWeek: 'Mondwoche',
    lunarRules: 'Mondwoche (Lunar Rules)',
    footer: 'Basierend auf den Lehren von Adano Ley & Atom Bergstrom • Berechnet mit Wahrer Sonnenzeit (True Solar Time)',
    footerTitle: 'Solar Nutrition App & Database',
  },

  // --- Windows ---
  windows: {
    Morning: '☀️ Morgen (Tree)',
    Midday: '🌞 Mittag (Bush/Vine)',
    Evening: '🌙 Abend (Root/Water)',
    activeWindow: 'Aktuell aktives Fenster',
    dawnTransition: 'Dawn Transition (11:30-12:30)',
    duskTransition: 'Dusk Transition (18:00-19:00)',
  },

  // --- Navigation ---
  nav: {
    dashboard: 'Wachstumszone',
    checker: 'Kombinations-Checker',
    recipes: 'Rezept-Datenbank',
    guide: 'Regeln & Wissen',
  },

  // --- Language Selector ---
  lang: {
    label: 'Sprache',
    de: 'Deutsch',
    en: 'English (GB)',
  },

  // --- Location Modal ---
  locationModal: {
    title: 'Standort festlegen',
    description: 'Der Standort wird benötigt, um die',
    descriptionBold: 'Wahre Sonnenzeit (True Solar Time)',
    descriptionEnd: 'exakt anhand Deines Längengrads zu berechnen.',
    gpsButton: 'Aktuellen GPS-Standort automatisch verwenden',
    orAddress: 'Oder Adresse eingeben',
    placeholder: 'z.B. Spickelstr. 22, 87437 Kempten oder Berlin...',
    searchButton: 'Standort übernehmen',
    searching: 'Suche läuft...',
    suggestions: 'Vorgeschlagene Standorte',
    errorGeoNotSupported: 'Geolokalisierung wird von Ihrem Browser leider nicht unterstützt.',
    errorDetails: 'Standortdetails konnten nicht abgerufen werden.',
    errorDenied: 'Zugriff auf den Standort wurde verweigert oder ist fehlgeschlagen.',
    errorNotFound: 'Kein Standort für "{{query}}" gefunden.',
  },

  // --- Time Window View ---
  timeWindow: {
    searchPlaceholder: 'Nahrungsmittel suchen...',
    weightLossFilter: 'Gewichtsverlust',
    weightLossOnly: 'Nur Gewichtsreduktion',
    currentWindow: 'Aktuell aktives Fenster',
    addToMeal: 'Zum Teller',
    removeFromMeal: 'Entfernen',
    principle: 'Prinzip',
    specialRules: 'Besondere Zeitregeln',
    noFoodsFound: 'Keine Nahrungsmittel für diesen Filter gefunden.',
  },

  // --- DB Category Names ---
  categories: {
    treeFruits: 'Baumfrüchte (Tree Fruits)',
    citrus: 'Zitrusfrüchte (09:00-11:00 Allein)',
    nuts: 'Nüsse & Samen',
    oilsMorning: 'Öle & Fette',
    spicesMorning: 'Gewürze & Süßungsmittel',
    specialMorning: 'Spezialnahrung & Tonika',
    spiritsMorning: 'Spirituosen (Baum)',
    vegetables: 'Strauchgemüse',
    grains: 'Getreide & Hülsenfrüchte',
    berries: 'Beeren & Melonen (15:00-17:00)',
    beveragesMidday: 'Getränke & Tee',
    dairy: 'Milchprodukte',
    landAnimals: 'Landtiere & Geflügel',
    freshwaterFish: 'Süßwasserfisch (Ausnahme Forelle)',
    herbs: 'Kräuter',
    oilsMidday: 'Öle & Fette',
    spicesMidday: 'Gewürze & Süßungsmittel',
    spiritsMidday: 'Spirituosen (Getreide/Strauch)',
    rootVegetables: 'Wurzelgemüse',
    groundLegumes: 'Erd-Hülsenfrüchte (Erdnüsse)',
    fungi: 'Pilze & Wasserpflanzen (CAM)',
    seafood: 'Meeresfrüchte & Fisch',
    exoticAnimal: 'Exotische Tierprodukte & Eier',
    oilsEvening: 'Öle & Fette',
    spicesEvening: 'Gewürze & Meersalz',
    specialEvening: 'Spezialnahrung & Tonika',
    spiritsEvening: 'Spirituosen (Erdpflanzen/Kartoffel)',
    anytime: 'Zeitneutrale Grundnahrungsmittel',
    spiritsAnytime: 'Spirituosen (Reis)',
  },

  // --- Window Metadata ---
  windowData: {
    morningName: 'Morning Window (Morgen)',
    morningRange: '00:00 bis 12:00 Solarzeit',
    morningPrinciple: 'Ernähre Dich von Nahrungsmitteln, die an BÄUMEN wachsen: Früchte & Nüsse.',
    morningSpecial: 'Zitrusfrüchte nur 09:00 - 11:00 (streng allein). Mandeln am besten als erste Nahrung (07:00-09:00).',
    middayName: 'Midday Window (Mittag)',
    middayRange: '12:00 bis 18:00 Solarzeit',
    middayPrinciple: 'Ernähre Dich von Pflanzen, die an STRÄUCHERN oder RANKEN wachsen (mind. 10cm hoch), Getreide sowie 2- und 4-beinigen Landtieren.',
    middaySpecial: 'Melonen nur 15:00 - 17:00 (streng allein). Beeren am besten 15:00 - 17:00.',
    eveningName: 'Evening Window (Abend)',
    eveningRange: '18:00 bis 24:00 Solarzeit',
    eveningPrinciple: 'Ernähre Dich von Nahrungsmitteln, die UNTER DER ERDE oder IM WASSER wachsen, Pilzen sowie Meeresfrüchten.',
    eveningSpecial: 'Keine Zitrus- oder Melonen-Regeln am Abend. Kartoffeln nur am Abend!',
    anytimeName: 'Any Time Window (Zeitneutral)',
    anytimeRange: 'Ganztägig verwendbar',
    anytimePrinciple: 'Zeitneutrale Nahrungsmittel, die zu jeder Tageszeit verzehrt und mit allen Fenstern kombiniert werden können.',
    anytimeSpecial: 'In Maßen verzehren. Perfekt zum Verfeinern.',
  },

  // --- Combination Checker ---
  checker: {
    title: 'Kombinations-Checker',
    subtitle: 'Wähle Nahrungsmittel aus den Wachstumszonen und prüfe, ob sie kompatibel sind.',
    currentMeal: 'Dein aktueller Teller',
    emptyMeal: 'Klicke in den Wachstumszonen auf ein Nahrungsmittel, um es dem Kombinations-Checker hinzuzufügen.',
    clearMeal: 'Teller leeren',
    checkResult: 'Kombinations-Analyse',
    addMoreFoods: 'Mindestens 2 Nahrungsmittel hinzufügen, um die Kombination zu prüfen.',
    fullMoonNote: 'Vollmond! Alle Kombinationen aus allen Wachstumszonen sind heute erlaubt.',
    transitionNote: 'Übergangszeit aktiv – Kombinationen aus angrenzenden Wachstumszonen sind erlaubt.',
  },

  // --- Recipe Catalog ---
  recipes: {
    title: 'Rezept-Datenbank',
    subtitle: '100% regelkonforme Rezepte für alle Wachstumszonen & Übergangszeiten.',
    searchPlaceholder: 'Rezept oder Zutaten suchen...',
    filterWindow: 'Fenster:',
    filterDiet: 'Ernährung:',
    filterAll: 'Alle',
    filterCurrent: '⚡ Jetzt Aktiv',
    filterMorning: '☀️ Morning',
    filterMidday: '🌞 Midday',
    filterEvening: '🌙 Evening',
    filterDawn: '🌅 Dawn',
    filterDusk: '🌆 Dusk',
    filterOmni: 'Mischkost',
    filterVeg: 'Vegetarisch',
    filterVegan: 'Vegan',
    noRecipes: 'Keine Rezepte für die gewählten Filter gefunden.',
    backToList: '← Zurück zur Rezeptübersicht',
    backHint: '(ESC / Backspace)',
    prepTime: 'Zubereitung:',
    min: 'Min.',
    difficulty: 'Schwierigkeit:',
    servings: 'Portionen:',
    ingredients: 'Zutaten',
    instructions: 'Zubereitung',
    tip: '💡 Solar Nutrition Praxistipp:',
    showRecipe: 'Rezept anzeigen',
    printTooltip: 'Drucken',
    favTooltip: 'Zu Favoriten hinzufügen',
  },

  // --- Food Detail Modal ---
  foodModal: {
    ruleLabel: 'Solar Nutrition Regel / Hinweis:',
    noRule: 'Dieses Nahrungsmittel fügt sich harmonisch in die zugeordnete Wachstumszone ein. Halte Dich an die allgemeine Regel der Zone.',
    forbiddenLabel: 'Streng verbotenes Nahrungsmittel:',
    forbiddenText: 'Nach den Regeln der Solar Nutrition sollte dieses Nahrungsmittel in der Ernährung vermieden werden.',
    close: 'Schließen',
    addToMeal: 'Zu Mahlzeit hinzufügen',
    alreadyInMeal: 'Bereits im Teller',
    weightLoss: 'Gewichtsverlust',
    windowLabel: {
      Morning: '☀️ Morning (Baum)',
      Midday: '🌞 Midday (Strauch)',
      Evening: '🌙 Evening (Wurzel/Wasser)',
      AnyTime: '🕊️ AnyTime (Zeitneutral)',
    },
  },

  // --- Rules Guide ---
  guide: {
    title: 'Regeln der Solar Nutrition',
    badge: 'Kompendium & Regelwerk',
    subtitle: 'Entwickelt von Adano Ley und überliefert durch Atom Bergstrom. Basierend auf der zirkadianen Biologie und den drei biologischen Wachstumszonen.',
    morningWindow: 'Morning Window',
    morningTime: '00:00 – 12:00 Solarzeit',
    morningDesc: 'Nahrungsmittel, die an BÄUMEN wachsen: Früchte, Nüsse, Samen, Baumöle (Avocadoöl, Kokosöl) und Arabica-Kaffee.',
    middayWindow: 'Midday Window',
    middayTime: '12:00 – 18:00 Solarzeit',
    middayDesc: 'Nahrungsmittel, die an STRÄUCHERN oder RANKEN wachsen (mind. 10 cm hoch), Getreide, 2- & 4-beinige Landtiere sowie Forelle.',
    eveningWindow: 'Evening Window',
    eveningTime: '18:00 – 24:00 Solarzeit',
    eveningDesc: 'Nahrungsmittel, die UNTER DER ERDE (Wurzeln), IM WASSER (Meeresfrüchte, Fisch, Algen), oder in Dunkelheit wachsen (Pilze, CAM-Pflanzen).',
    transitionsTitle: 'Die zwei Übergangszeiten (Transitions)',
    dawnTitle: '🌅 Dawn Transition (11:30 – 12:30 Solarzeit)',
    dawnDesc: 'In dieser Stunde überschneiden sich Morgen- und Mittagsenergie. Es dürfen Nahrungsmittel von Bäumen (Morning) mit Nahrungsmitteln von Sträuchern/Getreide (Midday) kombiniert werden. (z.B. Apfel mit Haferflocken).',
    duskTitle: '🌆 Dusk Transition (18:00 – 19:00 Solarzeit)',
    duskDesc: 'In dieser Stunde überschneiden sich Mittags- und Abendenergie. Es dürfen Nahrungsmittel von Sträuchern/Getreide (Midday) mit Nahrungsmitteln aus Erde/Wasser (Evening) kombiniert werden. (z.B. Brokkoli mit Kartoffeln).',
    exceptionsTitle: 'Besondere Ausnahmen & Tonika',
    kiwi: 'Kiwi & Passionsfrucht: Werden als Morning (Baum)-Früchte eingeordnet.',
    citrus: 'Zitrusfrüchte (09:00-11:00): Müssen immer STRENG ALLEIN gegessen werden.',
    melons: 'Melonen (15:00-17:00): Müssen immer STRENG ALLEIN gegessen werden.',
    almonds: 'Mandeln (07:00-09:00): Erste Nahrung des Tages (roh & eingeweicht).',
    cam: 'CAM-Pflanzen (Ananas, Aloe Vera): Gehören wegen Nachtstoffwechsel ins Evening-Fenster.',
    tonic: 'Adanos Cobalamin Tonic (Morning): Kaffee + Ahornsirup + dunkler Backkakao.',
    forbiddenTitle: 'Strenge Verbote',
    pepper: 'Schwarzer Pfeffer: Streng verboten! Einziger Pfefferersatz ist Cayennepfeffer.',
    meatDairy: 'Fleisch + Milch/Käse: Niemals Fleisch und Milchprodukte in einer Mahlzeit mischen.',
    meltedCheese: 'Geschmolzener Käse: Käse darf nicht stark erhitzt/geschmolzen werden.',
    carbonated: 'Kohlensäure & Frittiertes: Stark belastend für die Verdauung.',
  },

  // --- Combination Checker messages ---
  combinationMessages: {
    success: '✅ Hervorragende Kombination! Alle ausgewählten Nahrungsmittel passen perfekt in eine gemeinsame Wachstumszone.',
    warning: '⚠️ Das Mischen von Nahrungsmitteln aus verschiedenen Wachstumszonen ist außerhalb der Übergangszeiten (Dawn 11:30-12:30 / Dusk 18:00-19:00) nicht empfohlen.',
    fullMoon: '🌕 Vollmond! Heute sind alle Kombinationen aus allen Wachstumszonen erlaubt.',
    transition: '✅ Übergangszeit (Transition) aktiv – diese Kombination ist in der aktuellen Übergangszeit erlaubt.',
  },
} as const;
