export const en = {
  // --- App / Header ---
  app: {
    tagline: 'Solar Nutrition Database & App',
    quote: '"It\'s not WHAT you eat, but WHEN you eat it." – Based on the teachings of Adano Ley & Atom Bergstrom.',
    localTime: 'Local Time',
    trueSolarTime: 'True Solar Time',
    location: 'Location',
    setLocation: 'Set Location',
    currentPhase: 'Current Phase:',
    fullMoonDay: '🌕 Full Moon Day: All Growth Zones & combinations permitted!',
    lunarWeek: 'Lunar Week',
    lunarRules: 'Lunar Week (Lunar Rules)',
    footer: 'Based on the teachings of Adano Ley & Atom Bergstrom • Calculated with True Solar Time',
    footerTitle: 'Solar Nutrition App & Database',
  },

  // --- Windows ---
  windows: {
    Morning: '☀️ Morning (Tree)',
    Midday: '🌞 Midday (Bush/Vine)',
    Evening: '🌙 Evening (Root/Water)',
    activeWindow: 'Currently active window',
    dawnTransition: 'Dawn Transition (11:30-12:30)',
    duskTransition: 'Dusk Transition (18:00-19:00)',
  },

  // --- Navigation ---
  nav: {
    dashboard: 'Growth Zone',
    checker: 'Combination Checker',
    recipes: 'Recipe Database',
    guide: 'Rules & Knowledge',
  },

  // --- Language Selector ---
  lang: {
    label: 'Language',
    de: 'Deutsch',
    en: 'English (GB)',
  },

  // --- Location Modal ---
  locationModal: {
    title: 'Set Location',
    description: 'Your location is needed to calculate the',
    descriptionBold: 'True Solar Time (True Solar Time)',
    descriptionEnd: 'precisely based on your longitude.',
    gpsButton: 'Use current GPS location automatically',
    orAddress: 'Or enter an address',
    placeholder: 'e.g. 10 Downing Street, London or Manchester...',
    searchButton: 'Confirm location',
    searching: 'Searching...',
    suggestions: 'Suggested locations',
    errorGeoNotSupported: 'Geolocation is not supported by your browser.',
    errorDetails: 'Could not retrieve location details.',
    errorDenied: 'Access to location was denied or failed.',
    errorNotFound: 'No location found for "{{query}}".',
  },

  // --- Time Window View ---
  timeWindow: {
    searchPlaceholder: 'Search foods...',
    weightLossFilter: 'Weight Loss',
    weightLossOnly: 'Weight loss only',
    currentWindow: 'Currently active window',
    addToMeal: 'Add to plate',
    removeFromMeal: 'Remove',
    principle: 'Principle',
    specialRules: 'Special Timing Rules',
    noFoodsFound: 'No foods found for this filter.',
  },

  // --- DB Category Names ---
  categories: {
    treeFruits: 'Tree Fruits',
    citrus: 'Citrus Fruits (09:00-11:00 Alone)',
    nuts: 'Nuts & Seeds',
    oilsMorning: 'Oils & Fats',
    spicesMorning: 'Spices & Sweeteners',
    specialMorning: 'Special Foods & Tonics',
    spiritsMorning: 'Spirits (Tree)',
    vegetables: 'Bush Vegetables',
    grains: 'Grains & Legumes',
    berries: 'Berries & Melons (15:00-17:00)',
    beveragesMidday: 'Beverages & Tea',
    dairy: 'Dairy Products',
    landAnimals: 'Land Animals & Poultry',
    freshwaterFish: 'Freshwater Fish (Trout exception)',
    herbs: 'Herbs',
    oilsMidday: 'Oils & Fats',
    spicesMidday: 'Spices & Sweeteners',
    spiritsMidday: 'Spirits (Grain/Bush)',
    rootVegetables: 'Root Vegetables',
    groundLegumes: 'Ground Legumes (Peanuts)',
    fungi: 'Fungi & Water Plants (CAM)',
    seafood: 'Seafood & Fish',
    exoticAnimal: 'Exotic Animal Products & Eggs',
    oilsEvening: 'Oils & Fats',
    spicesEvening: 'Spices & Sea Salt',
    specialEvening: 'Special Foods & Tonics',
    spiritsEvening: 'Spirits (Root Plants/Potato)',
    anytime: 'Time-Neutral Staples',
    spiritsAnytime: 'Spirits (Rice)',
  },

  // --- Window Metadata ---
  windowData: {
    morningName: 'Morning Window',
    morningRange: '00:00 to 12:00 Solar Time',
    morningPrinciple: 'Eat foods that grow on TREES: fruits & nuts.',
    morningSpecial: 'Citrus fruits only 09:00 – 11:00 (strictly alone). Almonds best as first food (07:00-09:00).',
    middayName: 'Midday Window',
    middayRange: '12:00 to 18:00 Solar Time',
    middayPrinciple: 'Eat plants that grow on BUSHES or VINES (at least 10 cm above ground), grains, and 2- and 4-legged land animals.',
    middaySpecial: 'Melons only 15:00 – 17:00 (strictly alone). Berries best 15:00 – 17:00.',
    eveningName: 'Evening Window',
    eveningRange: '18:00 to 24:00 Solar Time',
    eveningPrinciple: 'Eat foods that grow UNDERGROUND or IN WATER, fungi, and seafood.',
    eveningSpecial: 'No citrus or melon rules in the evening. Potatoes only in the evening!',
    anytimeName: 'Any Time Window (Time-Neutral)',
    anytimeRange: 'Usable throughout the day',
    anytimePrinciple: 'Time-neutral foods that can be eaten at any time of day and combined with all windows.',
    anytimeSpecial: 'Use in moderation. Perfect for seasoning.',
  },

  // --- Combination Checker ---
  checker: {
    title: 'Combination Checker',
    subtitle: 'Select foods from the Growth Zones and check whether they are compatible.',
    currentMeal: 'Your current plate',
    emptyMeal: 'Click on a food in the Growth Zones to add it to the Combination Checker.',
    clearMeal: 'Clear plate',
    checkResult: 'Combination Analysis',
    addMoreFoods: 'Add at least 2 foods to check the combination.',
    fullMoonNote: 'Full Moon! All combinations from all Growth Zones are permitted today.',
    transitionNote: 'Transition time active – combinations from adjacent Growth Zones are permitted.',
  },

  // --- Recipe Catalog ---
  recipes: {
    title: 'Recipe Database',
    subtitle: '100% rule-compliant recipes for all Growth Zones & transition times.',
    searchPlaceholder: 'Search recipes or ingredients...',
    filterWindow: 'Window:',
    filterDiet: 'Diet:',
    filterAll: 'All',
    filterCurrent: '⚡ Active Now',
    filterMorning: '☀️ Morning',
    filterMidday: '🌞 Midday',
    filterEvening: '🌙 Evening',
    filterDawn: '🌅 Dawn',
    filterDusk: '🌆 Dusk',
    filterOmni: 'Omnivore',
    filterVeg: 'Vegetarian',
    filterVegan: 'Vegan',
    noRecipes: 'No recipes found for the selected filters.',
    backToList: '← Back to recipe overview',
    backHint: '(ESC / Backspace)',
    prepTime: 'Prep time:',
    min: 'min.',
    difficulty: 'Difficulty:',
    servings: 'Servings:',
    ingredients: 'Ingredients',
    instructions: 'Method',
    tip: '💡 Solar Nutrition Practical Tip:',
    showRecipe: 'View Recipe',
    printTooltip: 'Print',
    favTooltip: 'Add to favourites',
  },

  // --- Food Detail Modal ---
  foodModal: {
    ruleLabel: 'Solar Nutrition Rule / Note:',
    noRule: 'This food fits harmoniously into its assigned Growth Zone. Follow the general rule of the zone.',
    forbiddenLabel: 'Strictly Forbidden Food:',
    forbiddenText: 'According to the rules of Solar Nutrition, this food should be avoided in the diet.',
    close: 'Close',
    addToMeal: 'Add to meal',
    alreadyInMeal: 'Already on the plate',
    weightLoss: 'Weight Loss',
    windowLabel: {
      Morning: '☀️ Morning (Tree)',
      Midday: '🌞 Midday (Bush)',
      Evening: '🌙 Evening (Root/Water)',
      AnyTime: '🕊️ AnyTime (Time-Neutral)',
    },
  },

  // --- Rules Guide ---
  guide: {
    title: 'Rules of Solar Nutrition',
    badge: 'Compendium & Rule Book',
    subtitle: 'Developed by Adano Ley and passed on by Atom Bergstrom. Based on circadian biology and the three biological Growth Zones.',
    morningWindow: 'Morning Window',
    morningTime: '00:00 – 12:00 Solar Time',
    morningDesc: 'Foods that grow on TREES: fruits, nuts, seeds, tree oils (avocado oil, coconut oil) and Arabica coffee.',
    middayWindow: 'Midday Window',
    middayTime: '12:00 – 18:00 Solar Time',
    middayDesc: 'Foods that grow on BUSHES or VINES (at least 10 cm above ground), grains, 2- & 4-legged land animals, and trout.',
    eveningWindow: 'Evening Window',
    eveningTime: '18:00 – 24:00 Solar Time',
    eveningDesc: 'Foods that grow UNDERGROUND (roots), IN WATER (seafood, fish, algae), or in darkness (fungi, CAM plants).',
    transitionsTitle: 'The Two Transition Times',
    dawnTitle: '🌅 Dawn Transition (11:30 – 12:30 Solar Time)',
    dawnDesc: 'During this hour, morning and midday energies overlap. Foods from Trees (Morning) may be combined with foods from Bushes/Grains (Midday). (e.g. apple with porridge).',
    duskTitle: '🌆 Dusk Transition (18:00 – 19:00 Solar Time)',
    duskDesc: 'During this hour, midday and evening energies overlap. Foods from Bushes/Grains (Midday) may be combined with foods from Earth/Water (Evening). (e.g. broccoli with potatoes).',
    exceptionsTitle: 'Special Exceptions & Tonics',
    kiwi: 'Kiwi & Passion Fruit: Classified as Morning (Tree) fruits.',
    citrus: 'Citrus Fruits (09:00-11:00): Must always be eaten STRICTLY ALONE.',
    melons: 'Melons (15:00-17:00): Must always be eaten STRICTLY ALONE.',
    almonds: 'Almonds (07:00-09:00): First food of the day (raw & soaked).',
    cam: 'CAM Plants (Pineapple, Aloe Vera): Belong in the Evening window due to nocturnal metabolism.',
    tonic: "Adano's Cobalamin Tonic (Morning): Coffee + maple syrup + dark baking cacao.",
    forbiddenTitle: 'Strict Prohibitions',
    pepper: 'Black Pepper: Strictly forbidden! The only pepper substitute is Cayenne pepper.',
    meatDairy: 'Meat + Milk/Cheese: Never mix meat and dairy products in one meal.',
    meltedCheese: 'Melted Cheese: Cheese must not be strongly heated or melted.',
    carbonated: 'Carbonated Drinks & Deep-Fried Foods: Highly taxing on digestion.',
  },

  // --- Combination Checker messages ---
  combinationMessages: {
    success: '✅ Excellent combination! All selected foods fit perfectly into one Growth Zone.',
    warning: '⚠️ Mixing foods from different Growth Zones is not recommended outside transition times (Dawn 11:30-12:30 / Dusk 18:00-19:00).',
    fullMoon: '🌕 Full Moon! All combinations from all Growth Zones are permitted today.',
    transition: '✅ Transition time active – this combination is permitted during the current transition.',
  },
} as const;
