import type { Recipe } from '../types/solar';

export const PRELOADED_RECIPES: Recipe[] = [
  // ==========================================
  // MORNING RECIPES (00:00 - 12:00 Solarzeit) - TREE FOODS
  // ==========================================
  {
    id: 'morn-01',
    title: 'Sonnenaufgang Obst-Schale mit Ahornsirup & Kakaonibs',
    titleEN: 'Sunrise Orchard Bowl with Maple Syrup & Cacao Nibs',
    mealName: 'Sunrise Orchard Bowl',
    description: 'Eine vitalisierende Fruchtschale aus süßen Äpfeln, Pfirsichen, Banane und knackigen Mandeln, abgerundet mit Ahornsirup und dunklen Kakaonibs.',
    descriptionEN: 'A vitalising fruit bowl of sweet apples, peaches, banana and crunchy almonds, finished with maple syrup and dark cacao nibs.',
    timeWindow: 'Morning',
    diet: 'Vegan',
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    servings: 2,
    difficulty: 'Einfach',
    cuisine: 'International',
    cuisineEN: 'International',
    isPreloaded: true,
    tags: ['Schnell', 'Rohkost', 'Frühstück'],
    ingredients: [
      { name: 'Apfel (Apple)', nameEN: 'Apple', amount: '1 großer Apfel, gewürfelt', amountEN: '1 large apple, diced' },
      { name: 'Pfirsich (Peach)', nameEN: 'Peach', amount: '1 Pfirsich, in Scheiben', amountEN: '1 peach, sliced' },
      { name: 'Banane (Banana)', nameEN: 'Banana', amount: '1 reife Banane', amountEN: '1 ripe banana' },
      { name: 'Mandeln (Almonds)', nameEN: 'Almonds', amount: '30g eingeweichte, gehackte Mandeln', amountEN: '30g soaked, chopped almonds' },
      { name: 'Ahornsirup (Maple Syrup)', nameEN: 'Maple Syrup', amount: '1 EL', amountEN: '1 tbsp' },
      { name: 'Kakaobohnen (Cacao)', nameEN: 'Cacao Beans', amount: '1 TL Kakaonibs', amountEN: '1 tsp cacao nibs' },
    ],
    instructions: [
      'Die eingeweichten Mandeln grob hacken.',
      'Apfel, Pfirsich und Banane in mundgerechte Stücke schneiden.',
      'Das Obst in einer Schale anrichten und mit den Mandeln und Kakaonibs bestreuen.',
      'Mit einem Esslöffel reinem Ahornsirup beträufeln und sofort genießen.',
    ],
    instructionsEN: [
      'Coarsely chop the soaked almonds.',
      'Cut apple, peach, and banana into bite-sized pieces.',
      'Arrange fruit in a bowl and sprinkle with almonds and cacao nibs.',
      'Drizzle with a tablespoon of pure maple syrup and enjoy immediately.',
    ],
    tips: ['Mandeln am besten über Nacht in kaltem Wasser einweichen.'],
    tipsEN: ['Best to soak almonds overnight in cold water.'],
  },
  {
    id: 'morn-02',
    title: 'Adanos Cobalamin Tonic & Avocadobrot (Morgen-Kick)',
    titleEN: "Adano's Cobalamin Tonic & Avocado Toast (Morning Boost)",
    mealName: 'Adano B12 Boost & Avocado Toast',
    description: 'Das legendäre B12-Tonic von Adano Ley kombiniert mit cremigem Avocadobelag auf leicht getoastetem Reisbrot.',
    descriptionEN: "Adano Ley's legendary B12 tonic combined with creamy avocado topping on lightly toasted rice bread.",
    timeWindow: 'Morning',
    diet: 'Vegetarian',
    prepTimeMinutes: 10,
    cookTimeMinutes: 5,
    servings: 1,
    difficulty: 'Einfach',
    cuisine: 'Solar Specialty',
    cuisineEN: 'Solar Specialty',
    isPreloaded: true,
    tags: ['Tonic', 'B12-Booster', 'Energie'],
    ingredients: [
      { name: 'Kaffee (Coffee Arabica)', nameEN: 'Coffee (Arabica)', amount: '1 Tasse frischer Arabica-Kaffee', amountEN: '1 cup fresh Arabica coffee' },
      { name: 'Ahornsirup (Maple Syrup)', nameEN: 'Maple Syrup', amount: '1 EL', amountEN: '1 tbsp' },
      { name: 'Kakaobohnen (Cacao)', nameEN: 'Cacao Beans', amount: '1 TL dunkles Backkakaopulver', amountEN: '1 tsp dark baking cacao powder' },
      { name: 'Avocado', nameEN: 'Avocado', amount: '1/2 reife Avocado', amountEN: '1/2 ripe avocado' },
      { name: 'Salz (Diamond Crystal Kosher)', nameEN: 'Salt (Diamond Crystal Kosher)', amount: '1 Prise Kosher Salt', amountEN: '1 pinch Kosher salt' },
      { name: 'Reisnudeln (100% Reis)', nameEN: 'Rice Noodles (100% Rice)', amount: 'Oder zeitneutrales Reisgebäck/Brot', amountEN: 'Or time-neutral rice crackers/bread' },
    ],
    instructions: [
      'Den heißen Arabica-Kaffee mit Ahornsirup und dunklem Backkakao verrühren (Cobalamin Tonic).',
      'Die Halbe Avocado zerdrücken und mit einer Prise Diamond Crystal Kosher Salt abschmecken.',
      'Auf zeitneutralem Reisbrot verstreichen und zusammen mit dem Tonic servieren.',
    ],
    instructionsEN: [
      'Stir maple syrup and dark baking cacao into hot Arabica coffee (Cobalamin Tonic).',
      'Mash half an avocado and season with a pinch of Diamond Crystal Kosher salt.',
      'Spread onto time-neutral rice bread and serve alongside the tonic.',
    ],
    tips: ['Verwende ausschließlich dunklen, ungesüßten Backkakao für das Tonic.'],
    tipsEN: ['Use strictly dark, unsweetened baking cacao for the tonic.'],
  },
  {
    id: 'morn-03',
    title: 'Tropische Mango-Papaya Schale mit Kokos-Splittern & Pekannüssen',
    titleEN: 'Tropical Mango & Papaya Bowl with Coconut Shavings & Pecans',
    mealName: 'Tropical Morning Mango Bowl',
    description: 'Sonnenverwöhnte Mangowürfel und Papaya verfeinert mit gehackten Pekannüssen, Kokosöl und echtem Ahornsirup.',
    descriptionEN: 'Sun-ripened diced mango and papaya enhanced with chopped pecans, coconut oil, and pure maple syrup.',
    timeWindow: 'Morning',
    diet: 'Vegan',
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    servings: 2,
    difficulty: 'Einfach',
    cuisine: 'Tropisch',
    cuisineEN: 'Tropical',
    isPreloaded: true,
    tags: ['Morgen', 'Rohkost', 'Tropisch', 'Vitamine'],
    ingredients: [
      { name: 'Mango', nameEN: 'Mango', amount: '1 reife Mango, gewürfelt', amountEN: '1 ripe mango, diced' },
      { name: 'Papaya', nameEN: 'Papaya', amount: '1/2 kleine Papaya', amountEN: '1/2 small papaya' },
      { name: 'Pekannüsse (Pecans)', nameEN: 'Pecans', amount: '30g Pekannüsse, gehackt', amountEN: '30g pecans, chopped' },
      { name: 'Kokosnuss (Coconut)', nameEN: 'Coconut', amount: '2 EL Kokosraspel oder Kokosöl', amountEN: '2 tbsp desiccated coconut or coconut oil' },
      { name: 'Ahornsirup (Maple Syrup)', nameEN: 'Maple Syrup', amount: '1 EL Ahornsirup', amountEN: '1 tbsp maple syrup' },
    ],
    instructions: [
      'Mango und Papaya schälen, entkernen und in kleine Würfel schneiden.',
      'In einer Frühstücksschale vermengen.',
      'Mit gehackten Pekannüssen und Kokosraspeln bestreuen.',
      'Mit einem Esslöffel reinem Ahornsirup beträufeln.',
    ],
    instructionsEN: [
      'Peel, seed, and dice the mango and papaya.',
      'Combine in a breakfast bowl.',
      'Top with chopped pecans and desiccated coconut.',
      'Drizzle with a tablespoon of pure maple syrup.',
    ],
  },
  {
    id: 'morn-04',
    title: 'Eingeweichte Morgen-Mandeln mit Datteln & Feigen-Quartett',
    titleEN: 'Soaked Morning Almonds with Date & Fig Quartet',
    mealName: 'Soaked Almond & Fig Power Breakfast',
    description: 'Adanos magensäureregulierende Morgen-Mandeln kombiniert mit süßen getrockneten Feigen, Datteln und Walnüssen.',
    descriptionEN: "Adano's stomach-acid regulating morning almonds combined with sweet dried figs, dates, and walnuts.",
    timeWindow: 'Morning',
    diet: 'Vegan',
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    difficulty: 'Einfach',
    cuisine: 'Solar Specialty',
    cuisineEN: 'Solar Specialty',
    isPreloaded: true,
    tags: ['Mandeln', 'Salzsäure-Balance', 'Rohkost'],
    ingredients: [
      { name: 'Mandeln (Almonds)', nameEN: 'Almonds', amount: '15-20 rohe, über Nacht eingeweichte Mandeln', amountEN: '15-20 raw almonds soaked overnight' },
      { name: 'Feige (Fig)', nameEN: 'Fig', amount: '2 frische oder getrocknete Feigen', amountEN: '2 fresh or dried figs' },
      { name: 'Dattel (Date)', nameEN: 'Date', amount: '2 Medjool-Datteln', amountEN: '2 Medjool dates' },
      { name: 'Walnüsse (Walnuts)', nameEN: 'Walnuts', amount: '20g Walnusskerne', amountEN: '20g walnut halves' },
      { name: 'Vanille (Vanilla)', nameEN: 'Vanilla', amount: '1 Prise echte gemahlene Vanille', amountEN: '1 pinch real ground vanilla' },
    ],
    instructions: [
      'Die eingeweichten Mandeln von der Haut befreien oder direkt gründlich kauen (ideal 07:00-09:00 Uhr Solarzeit).',
      'Feigen und Datteln klein schneiden.',
      'Zusammen mit den Walnüssen und der echten Vanille genießen.',
    ],
    instructionsEN: [
      'Skin the soaked almonds or chew thoroughly (ideal between 07:00 and 09:00 Solar Time).',
      'Chop the figs and dates.',
      'Enjoy together with walnuts and genuine ground vanilla.',
    ],
    tips: ['Mandeln am Morgen setzen den perfekten Salzsäure-Spiegel für den Tag.'],
    tipsEN: ['Almonds in the morning set the perfect stomach acid balance for the day.'],
  },
  {
    id: 'morn-05',
    title: 'Zitrus-Elixier des Morgens (Grapefruit & Orange)',
    titleEN: 'Citrus Morning Elixir (Grapefruit & Orange)',
    mealName: 'Citrus Morning Solitude',
    description: 'Erfrischendes Zitrusfrüchte-Frühstück aus saftigen Grapefruit- und Orangen-Spalten. Achtung: Strikte Regel zum Verzehr!',
    descriptionEN: 'Refreshing citrus breakfast of juicy grapefruit and orange segments. Note: Strict consumption rule!',
    timeWindow: 'Morning',
    diet: 'Vegan',
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    difficulty: 'Einfach',
    cuisine: 'Solar Specialty',
    cuisineEN: 'Solar Specialty',
    isPreloaded: true,
    tags: ['Zitrus', '09:00-11:00', 'Streng Allein'],
    ingredients: [
      { name: 'Grapefruit', nameEN: 'Grapefruit', amount: '1 rosa Grapefruit', amountEN: '1 pink grapefruit' },
      { name: 'Orange', nameEN: 'Orange', amount: '1 saftige Orange', amountEN: '1 juicy orange' },
      { name: 'Zitrone (Lemon)', nameEN: 'Lemon', amount: 'Ein paar Spritzer Zitronensaft', amountEN: 'A few squeezes of lemon juice' },
    ],
    instructions: [
      'Grapefruit und Orange filetieren.',
      'Die Zitrusfrüchte in einer Schale anrichten.',
      'Zwischen 09:00 und 11:00 Solarzeit genießen.',
    ],
    instructionsEN: [
      'Segment the grapefruit and orange.',
      'Arrange the citrus fruit segments in a bowl.',
      'Enjoy strictly between 09:00 and 11:00 Solar Time.',
    ],
    tips: ['STRENG ALLEIN VERZEHREN! Zitrusfrüchte dürfen niemals mit Fetten, Nüssen oder anderen Früchten kombiniert werden.'],
    tipsEN: ['EAT STRICTLY ALONE! Citrus fruits must never be combined with fats, nuts, or other fruits.'],
  },

  // ==========================================
  // MIDDAY RECIPES (12:00 - 18:00 Solarzeit) - BUSH & VINE & LAND ANIMALS
  // ==========================================
  {
    id: 'mid-01',
    title: 'Mediterrane Gemüse-Pfanne mit Feta & Olivenöl',
    titleEN: 'Mediterranean Veggie Stir-Fry with Feta & Olive Oil',
    mealName: 'Mediterranean Bush & Vine Saute',
    description: 'Knackiger Brokkoli, Zucchini und Zucchini-Würfel auf den Punkt in Olivenöl geschwenkt, garniert mit Schafskäse und Basilikum.',
    descriptionEN: 'Crisp broccoli, courgette, and bell peppers sautéed to perfection in olive oil, topped with feta and fresh basil.',
    timeWindow: 'Midday',
    diet: 'Vegetarian',
    prepTimeMinutes: 15,
    cookTimeMinutes: 12,
    servings: 2,
    difficulty: 'Einfach',
    cuisine: 'Mediterran',
    cuisineEN: 'Mediterranean',
    isPreloaded: true,
    tags: ['Warm', 'Schnell', 'Low Carb'],
    ingredients: [
      { name: 'Brokkoli (Broccoli)', nameEN: 'Broccoli', amount: '200g in Röschen', amountEN: '200g cut into florets' },
      { name: 'Zucchini', nameEN: 'Courgette (Zucchini)', amount: '1 kleine Zucchini', amountEN: '1 small courgette' },
      { name: 'Paprika (Bell Pepper)', nameEN: 'Bell Pepper', amount: '1 rote Paprika', amountEN: '1 red bell pepper' },
      { name: 'Olivenöl (Olive Oil)', nameEN: 'Olive Oil', amount: '2 EL', amountEN: '2 tbsp' },
      { name: 'Käse (Cheese)', nameEN: 'Cheese', amount: '50g Feta (nicht geschmolzen!)', amountEN: '50g feta (unmelted!)' },
      { name: 'Basilikum (Basil)', nameEN: 'Basil', amount: '1 Handvoll frisches Basilikum', amountEN: '1 handful fresh basil' },
      { name: 'Cayennepfeffer (Cayenne Pepper)', nameEN: 'Cayenne Pepper', amount: '1 Prise', amountEN: '1 pinch' },
      { name: 'Salz (Diamond Crystal Kosher)', nameEN: 'Salt (Diamond Crystal Kosher)', amount: '1 Prise Kosher Salt', amountEN: '1 pinch Kosher salt' },
    ],
    instructions: [
      'Das Gemüse in gleichmäßige Stücke schneiden.',
      'Olivenöl in einer Pfanne sanft erhitzen und Paprika, Brokkoli sowie Zucchini 8-10 Minuten dünsten.',
      'Mit Diamond Crystal Kosher Salt und einer Prise Cayennepfeffer (oder dreifach gefiltertem Pfeffersud) würzen.',
      'Von der Hitze nehmen, mit zerbröckeltem Feta und frischem Basilikum bestreuen und sofort servieren.',
    ],
    instructionsEN: [
      'Chop the vegetables into uniform pieces.',
      'Gently heat olive oil in a pan and sauté bell pepper, broccoli, and courgette for 8-10 minutes.',
      'Season with Diamond Crystal Kosher salt and a pinch of cayenne pepper.',
      'Remove from heat, crumble feta over the top with fresh basil, and serve immediately.',
    ],
    tips: ['Der Käse darf nicht stark schmelzen (Solar Nutrition Regel: kein geschmolzener Käse).'],
    tipsEN: ['The cheese must not be melted (Solar Nutrition rule: no melted cheese).'],
  },
  {
    id: 'mid-02',
    title: 'Zartes Hähnchenbrust-Filet mit Kräuter-Quinoa',
    titleEN: 'Tender Chicken Breast Fillet with Herbed Quinoa',
    mealName: 'Herbed Quinoa & Chicken Zenith Bowl',
    description: 'Saftiges Hähnchenfilet aus der Pfanne auf fluffiger Kräuter-Quinoa mit gedünstetem Spinat und Koriander.',
    descriptionEN: 'Pan-seared juicy chicken fillet served over fluffy herb quinoa with wilted spinach and coriander.',
    timeWindow: 'Midday',
    diet: 'Omnivore',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 2,
    difficulty: 'Mittel',
    cuisine: 'International',
    cuisineEN: 'International',
    isPreloaded: true,
    tags: ['Proteine', 'Hauptgericht', 'Gesund'],
    ingredients: [
      { name: 'Hähnchen (Chicken)', nameEN: 'Chicken', amount: '300g Hähnchenbrustfilet', amountEN: '300g chicken breast fillet' },
      { name: 'Quinoa', nameEN: 'Quinoa', amount: '120g Quinoa', amountEN: '120g quinoa' },
      { name: 'Spinat (Spinach)', nameEN: 'Spinach', amount: '150g frischer Spinat', amountEN: '150g fresh spinach' },
      { name: 'Olivenöl (Olive Oil)', nameEN: 'Olive Oil', amount: '2 EL', amountEN: '2 tbsp' },
      { name: 'Koriander (Cilantro)', nameEN: 'Coriander / Cilantro', amount: '1 EL gehackter Koriander', amountEN: '1 tbsp chopped coriander' },
      { name: 'Cayennepfeffer (Cayenne Pepper)', nameEN: 'Cayenne Pepper', amount: '1 Prise', amountEN: '1 pinch' },
      { name: 'Salz (Diamond Crystal Kosher)', nameEN: 'Salt (Diamond Crystal Kosher)', amount: '1/2 TL Kosher Salt', amountEN: '1/2 tsp Kosher salt' },
    ],
    instructions: [
      'Quinoa gründlich abspülen und in der doppelten Menge Wasser ca. 15 Minuten köcheln lassen.',
      'Hähnchenbrust in Olivenöl bei mittlerer Hitze von beiden Seiten ca. 6-8 Minuten durchbraten.',
      'Spinat in den letzten 3 Minuten kurz in die Pfanne geben, bis er zusammenfällt.',
      'Mit Kosher Salt und Cayennepfeffer (oder dreifach gefiltertem Pfeffersud) würzen und auf der Quinoa mit Koriander servieren.',
    ],
    instructionsEN: [
      'Rinse quinoa thoroughly and simmer in twice the volume of water for about 15 minutes.',
      'Pan-fry chicken breast in olive oil over medium heat for 6-8 minutes per side.',
      'Add spinach to the pan in the last 3 minutes until wilted.',
      'Season with Kosher salt and cayenne pepper, serving over quinoa topped with fresh coriander.',
    ],
    tips: ['Fleisch niemals mit Milchprodukten (Milch/Käse) kombinieren!'],
    tipsEN: ['Never combine meat with dairy products (milk/cheese)!'],
  },
  {
    id: 'mid-de-01',
    title: 'Deutsches Landhähnchen mit Dinkelgraupen & Kräuter-Rosenkohl',
    titleEN: 'German Farmhouse Chicken with Pearl Spelt & Herb Sprouts',
    mealName: 'German Rustic Chicken & Spelt',
    description: 'Traditionell deutsches Mittagsgericht: Saftige Hähnchenbrust in Olivenöl mit duftendem Rosmarin, serviert auf fluffigem Dinkel und zart gedünstetem Rosenkohl.',
    descriptionEN: 'Traditional German midday meal: Juicy chicken breast sautéed with rosemary, served over fluffy spelt and tender Brussels sprouts.',
    timeWindow: 'Midday',
    diet: 'Omnivore',
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 2,
    difficulty: 'Mittel',
    cuisine: 'Deutsch',
    cuisineEN: 'German',
    isPreloaded: true,
    tags: ['Deutsch', 'Mittagessen', 'Herzhaft', 'Proteine'],
    ingredients: [
      { name: 'Hähnchen (Chicken)', nameEN: 'Chicken', amount: '300g frisches Hähnchenbrustfilet', amountEN: '300g fresh chicken breast fillet' },
      { name: 'Dinkel (Spelt)', nameEN: 'Spelt', amount: '120g Dinkel-Perlgraupen', amountEN: '120g pearl spelt' },
      { name: 'Rosenkohl (Brussels Sprouts)', nameEN: 'Brussels Sprouts', amount: '200g halbierter Rosenkohl', amountEN: '200g halved Brussels sprouts' },
      { name: 'Olivenöl (Olive Oil)', nameEN: 'Olive Oil', amount: '2 EL', amountEN: '2 tbsp' },
      { name: 'Rosmarin (Rosemary)', nameEN: 'Rosemary', amount: '1 Zweig frischer Rosmarin', amountEN: '1 sprig fresh rosemary' },
      { name: 'Salz (Diamond Crystal Kosher)', nameEN: 'Salt (Diamond Crystal Kosher)', amount: '1/2 TL Kosher Salt', amountEN: '1/2 tsp Kosher salt' },
      { name: 'Dreifach gefilterter Pfeffersud', nameEN: 'Filtered Pepper Extract', amount: '1 TL (oder 1 Prise Cayennepfeffer)', amountEN: '1 tsp (or 1 pinch cayenne pepper)' },
    ],
    instructions: [
      'Dinkelgraupen in reichlich Salzwasser ca. 20 Minuten gar kochen.',
      'Rosenkohl putzen, halbieren und in Olivenöl bei mittlerer Hitze 10 Minuten knackig braten.',
      'Hähnchenbrust mit Rosmarin in Olivenöl von beiden Seiten goldbraun anbraten.',
      'Mit Diamond Crystal Kosher Salt und dreifach gefiltertem Pfeffersud (oder Cayennepfeffer) abschmecken und warm servieren.',
    ],
    instructionsEN: [
      'Boil pearl spelt in salted water for about 20 minutes until tender.',
      'Trim and halve Brussels sprouts, frying in olive oil over medium heat for 10 minutes.',
      'Pan-fry chicken breast with rosemary in olive oil until golden brown on both sides.',
      'Season with Kosher salt and cayenne pepper, serving warm.',
    ],
  },
  {
    id: 'mid-it-01',
    title: 'Pasta Pomodoro e Zucchine con Basilico (Italienische Busch-Pasta)',
    titleEN: 'Pasta Pomodoro e Zucchine con Basilico (Italian Bush Pasta)',
    mealName: 'Italian Vine & Bush Pasta',
    description: 'Klassische italienische Pasta aus 100% Hartweizengrieß mit fruchtiger Tomaten-Salsa, knackigen Zucchini-Würfeln und frischem Basilikum.',
    descriptionEN: 'Classic Italian durum wheat pasta with fruity tomato salsa, crisp courgette cubes, and fresh basil.',
    timeWindow: 'Midday',
    diet: 'Vegan',
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 2,
    difficulty: 'Einfach',
    cuisine: 'Italienisch',
    cuisineEN: 'Italian',
    isPreloaded: true,
    tags: ['Italienisch', 'Pasta', 'Schnell', 'Vegan'],
    ingredients: [
      { name: 'Semolina Durum Wheat Pasta', nameEN: 'Semolina Durum Wheat Pasta', amount: '180g Penne oder Rigatoni', amountEN: '180g penne or rigatoni' },
      { name: 'Tomate (Tomato)', nameEN: 'Tomato', amount: '3 reife Strauchtomaten, gewürfelt', amountEN: '3 ripe vine tomatoes, diced' },
      { name: 'Zucchini', nameEN: 'Courgette (Zucchini)', amount: '1 mittlere Zucchini, gewürfelt', amountEN: '1 medium courgette, diced' },
      { name: 'Olivenöl (Olive Oil)', nameEN: 'Olive Oil', amount: '3 EL kaltgepresstes Olivenöl', amountEN: '3 tbsp extra virgin olive oil' },
      { name: 'Basilikum (Basil)', nameEN: 'Basil', amount: '1 Handvoll frisches Basilikum', amountEN: '1 handful fresh basil' },
      { name: 'Salz (Diamond Crystal Kosher)', nameEN: 'Salt (Diamond Crystal Kosher)', amount: '1/2 TL Kosher Salt', amountEN: '1/2 tsp Kosher salt' },
      { name: 'Dreifach gefilterter Pfeffersud', nameEN: 'Filtered Pepper Extract', amount: '1 TL (oder 1 Prise Cayennepfeffer)', amountEN: '1 tsp (or 1 pinch cayenne)' },
    ],
    instructions: [
      'Pasta in kochendem Salzwasser al dente garen.',
      'In einer großen Pfanne Olivenöl erhitzen, Zucchiniwürfel 5 Minuten anbraten, dann die Strauchtomaten dazugeben.',
      'Die Sauce 5 Minuten leicht einköcheln lassen, mit Diamond Crystal Kosher Salt und Pfeffersud/Cayennepfeffer abschmecken.',
      'Die Pasta direkt in die Pfanne geben, mit frischem Basilikum schwenken und sofort servieren.',
    ],
    instructionsEN: [
      'Cook pasta in boiling salted water until al dente.',
      'Heat olive oil in a skillet, sauté diced courgette for 5 minutes, then add diced vine tomatoes.',
      'Simmer sauce for 5 minutes, seasoning with Kosher salt and cayenne pepper.',
      'Toss cooked pasta into the pan with fresh basil leaves and serve hot.',
    ],
  },
  {
    id: 'mid-fr-01',
    title: 'Poulet aux Herbes de Provence mit Grünen Bohnen',
    titleEN: 'Poulet aux Herbes de Provence with French Green Beans',
    mealName: 'French Herb Chicken & Haricots Verts',
    description: 'Französischer Landhausstil: Zartes Hähnchenbrustfilet in Nativ-Olivenöl mit Kräutern der Provence, serviert auf fein gedünsteten grünen Bohnen.',
    descriptionEN: 'French country classic: Tender chicken breast in extra virgin olive oil with Herbes de Provence over lightly steamed green beans.',
    timeWindow: 'Midday',
    diet: 'Omnivore',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 2,
    difficulty: 'Mittel',
    cuisine: 'Französisch',
    cuisineEN: 'French',
    isPreloaded: true,
    tags: ['Französisch', 'Kräuter', 'Low Carb', 'Gourmet'],
    ingredients: [
      { name: 'Hähnchen (Chicken)', nameEN: 'Chicken', amount: '300g Hähnchenbrustfilet', amountEN: '300g chicken breast fillet' },
      { name: 'Grüne Bohnen (Green Beans)', nameEN: 'Green Beans', amount: '250g frische grüne Bohnen', amountEN: '250g fresh green beans' },
      { name: 'Olivenöl (Olive Oil)', nameEN: 'Olive Oil', amount: '2 EL', amountEN: '2 tbsp' },
      { name: 'Thymian (Thyme)', nameEN: 'Thyme', amount: '1 TL frischer Thymian', amountEN: '1 tsp fresh thyme' },
      { name: 'Rosmarin (Rosemary)', nameEN: 'Rosemary', amount: '1 TL frischer Rosmarin', amountEN: '1 tsp fresh rosemary' },
      { name: 'Salz (Diamond Crystal Kosher)', nameEN: 'Salt (Diamond Crystal Kosher)', amount: '1/2 TL Kosher Salt', amountEN: '1/2 tsp Kosher salt' },
      { name: 'Dreifach gefilterter Pfeffersud', nameEN: 'Filtered Pepper Extract', amount: '1 TL (oder Cayennepfeffer)', amountEN: '1 tsp (or cayenne pepper)' },
    ],
    instructions: [
      'Grüne Bohnen in Salzwasser ca. 8 Minuten blanchieren und in kaltem Wasser abschrecken.',
      'Hähnchenbrustfilet in Olivenöl mit Thymian und Rosmarin braten, bis es saftig durchgegart ist.',
      'Bohnen kurz in der Kräuterpfanne schwenken.',
      'Mit Kosher Salt und dreifach gefiltertem Pfeffersud oder Cayennepfeffer würzen und anrichten.',
    ],
    instructionsEN: [
      'Blanch green beans in salted water for 8 minutes and refresh in cold water.',
      'Pan-fry chicken breast in olive oil with thyme and rosemary until juicy and cooked through.',
      'Toss green beans briefly in the pan juices.',
      'Season with Kosher salt and cayenne pepper before serving.',
    ],
  },
  {
    id: 'mid-el-01',
    title: 'Griechisches Pfannengemüse mit Feta & Oregano',
    titleEN: 'Greek Sautéed Vegetables with Feta & Oregano',
    mealName: 'Greek Bush Saute with Feta',
    description: 'Griechischer Gemüsetraum aus bunter Paprika, Auberginen und Zucchini in Olivenöl, bestreut mit feinem Schafskäse und duftendem Oregano.',
    descriptionEN: 'Greek vegetable medley of colorful bell peppers, aubergine, and courgette in olive oil, topped with crumbled feta and aromatic oregano.',
    timeWindow: 'Midday',
    diet: 'Vegetarian',
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 2,
    difficulty: 'Einfach',
    cuisine: 'Griechisch',
    cuisineEN: 'Greek',
    isPreloaded: true,
    tags: ['Griechisch', 'Gemüse', 'Vegetarisch', 'Schnell'],
    ingredients: [
      { name: 'Paprika (Bell Pepper)', nameEN: 'Bell Pepper', amount: '1 rote & 1 gelbe Paprika', amountEN: '1 red & 1 yellow bell pepper' },
      { name: 'Zucchini', nameEN: 'Courgette (Zucchini)', amount: '1 Zucchini', amountEN: '1 courgette' },
      { name: 'Auberginen (Eggplant)', nameEN: 'Aubergine (Eggplant)', amount: '1/2 kleine Aubergine', amountEN: '1/2 small aubergine' },
      { name: 'Käse (Cheese)', nameEN: 'Cheese', amount: '60g Feta (Schafskäse)', amountEN: '60g feta cheese' },
      { name: 'Olivenöl (Olive Oil)', nameEN: 'Olive Oil', amount: '3 EL', amountEN: '3 tbsp' },
      { name: 'Oregano', nameEN: 'Oregano', amount: '1 EL frischer Oregano', amountEN: '1 tbsp fresh oregano' },
      { name: 'Salz (Diamond Crystal Kosher)', nameEN: 'Salt (Diamond Crystal Kosher)', amount: '1/2 TL Kosher Salt', amountEN: '1/2 tsp Kosher salt' },
      { name: 'Dreifach gefilterter Pfeffersud', nameEN: 'Filtered Pepper Extract', amount: '1 TL (oder Cayennepfeffer)', amountEN: '1 tsp (or cayenne pepper)' },
    ],
    instructions: [
      'Gemüse in mundgerechte Stücke schneiden.',
      'Olivenöl in einer großen Pfanne erhitzen, Auberginen, Paprika und Zucchini nacheinander anbraten.',
      'Mit Kosher Salt, Oregano und dreifach gefiltertem Pfeffersud oder Cayennepfeffer abschmecken.',
      'Pfanne vom Herd nehmen und den Feta kalt darüber krümeln (nicht schmelzen lassen!).',
    ],
    instructionsEN: [
      'Cut vegetables into bite-sized pieces.',
      'Heat olive oil in a skillet and sauté aubergine, bell peppers, and courgette.',
      'Season with Kosher salt, oregano, and cayenne pepper.',
      'Remove from heat and crumble cold feta over the top (do not melt!).',
    ],
  },
  {
    id: 'mid-asia-01',
    title: 'Asiatische Tofu-Zucchini-Pfanne mit Sesam & Tamari',
    titleEN: 'Asian Tofu & Courgette Stir-Fry with Sesame & Tamari',
    mealName: 'Asian Tofu & Bush Saute',
    description: 'Asiatisch inspirierte Wok-Pfanne aus gebratenem Tofu, Paprika und Zucchini in duftendem Sesamöl und echter Tamari-Sojasauce.',
    descriptionEN: 'Asian-inspired wok stir-fry of seared tofu, bell peppers, and courgette in fragrant sesame oil and tamari soy sauce.',
    timeWindow: 'Midday',
    diet: 'Vegan',
    prepTimeMinutes: 15,
    cookTimeMinutes: 12,
    servings: 2,
    difficulty: 'Einfach',
    cuisine: 'Asiatisch',
    cuisineEN: 'Asian',
    isPreloaded: true,
    tags: ['Asiatisch', 'Wok', 'Vegan', 'Proteine'],
    ingredients: [
      { name: 'Tofu & Tempeh', nameEN: 'Tofu & Tempeh', amount: '200g fester Naturtofu, gewürfelt', amountEN: '200g firm tofu, diced' },
      { name: 'Zucchini', nameEN: 'Courgette (Zucchini)', amount: '1 Zucchini, in Scheiben', amountEN: '1 courgette, sliced' },
      { name: 'Paprika (Bell Pepper)', nameEN: 'Bell Pepper', amount: '1 rote Paprika, in Streifen', amountEN: '1 red bell pepper, sliced' },
      { name: 'Sesamöl (Sesame Oil)', nameEN: 'Sesame Oil', amount: '2 EL Sesamöl', amountEN: '2 tbsp sesame oil' },
      { name: 'Tamari / Sojasauce', nameEN: 'Tamari / Soy Sauce', amount: '2 EL Tamari', amountEN: '2 tbsp tamari' },
      { name: 'Salz (Diamond Crystal Kosher)', nameEN: 'Salt (Diamond Crystal Kosher)', amount: '1 Prise Kosher Salt', amountEN: '1 pinch Kosher salt' },
      { name: 'Cayennepfeffer (Cayenne Pepper)', nameEN: 'Cayenne Pepper', amount: '1/2 TL Cayennepfeffer', amountEN: '1/2 tsp cayenne pepper' },
    ],
    instructions: [
      'Tofu trocken tupfen und in Würfel schneiden.',
      'Sesamöl im Wok erhitzen und den Tofu knusprig anbraten.',
      'Paprika und Zucchini dazugeben und 5 Minuten knackig pfannenrühren.',
      'Mit Tamari, Diamond Crystal Kosher Salt und Cayennepfeffer ablöschen und servieren.',
    ],
    instructionsEN: [
      'Pat tofu dry and cut into cubes.',
      'Heat sesame oil in a wok and sear tofu until golden.',
      'Add bell pepper and courgette, stir-frying for 5 minutes.',
      'Deglaze with tamari, Kosher salt, and cayenne pepper before serving.',
    ],
  },
  {
    id: 'mid-03',
    title: 'Deftiger Linsen-Kürbis-Topf mit Rosmarin & Thymian',
    titleEN: 'Hearty Lentil & Pumpkin Stew with Rosemary & Thyme',
    mealName: 'Hearty Bush Lentil & Pumpkin Stew',
    description: 'Sättigender Mittags-Eintopf aus braunen Linsen, Hokkaido-Kürbis und Brokkoli, abgeschmeckt mit frischen Kräutern.',
    descriptionEN: 'Filling midday stew of brown lentils, Hokkaido pumpkin, and broccoli, seasoned with fresh garden herbs.',
    timeWindow: 'Midday',
    diet: 'Vegan',
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 2,
    difficulty: 'Einfach',
    cuisine: 'International',
    cuisineEN: 'International',
    isPreloaded: true,
    tags: ['Linsen', 'Kürbis', 'Vegan', 'Herzhaft'],
    ingredients: [
      { name: 'Linsen (Lentils)', nameEN: 'Lentils', amount: '150g braune Linsen', amountEN: '150g brown lentils' },
      { name: 'Kürbis (Pumpkin)', nameEN: 'Pumpkin', amount: '200g Hokkaido-Kürbis, gewürfelt', amountEN: '200g Hokkaido pumpkin, diced' },
      { name: 'Brokkoli (Broccoli)', nameEN: 'Broccoli', amount: '150g Brokkoliröschen', amountEN: '150g broccoli florets' },
      { name: 'Olivenöl (Olive Oil)', nameEN: 'Olive Oil', amount: '2 EL', amountEN: '2 tbsp' },
      { name: 'Rosmarin (Rosemary)', nameEN: 'Rosemary', amount: '1 TL frischer Rosmarin', amountEN: '1 tsp fresh rosemary' },
      { name: 'Salz (Diamond Crystal Kosher)', nameEN: 'Salt (Diamond Crystal Kosher)', amount: '1 TL Kosher Salt', amountEN: '1 tsp Kosher salt' },
      { name: 'Dreifach gefilterter Pfeffersud', nameEN: 'Filtered Pepper Extract', amount: '1 TL (oder Cayennepfeffer)', amountEN: '1 tsp (or cayenne pepper)' },
    ],
    instructions: [
      'Linsen gründlich abspülen und in ca. 400ml Wasser 20 Minuten garen.',
      'Kürbiswürfel und Brokkoli in Olivenöl dünsten und unter die Linsen heben.',
      'Mit Rosmarin, Kosher Salt und dreifach gefiltertem Pfeffersud (oder Cayennepfeffer) würzen.',
    ],
    instructionsEN: [
      'Rinse lentils and simmer in 400ml water for 20 minutes.',
      'Sauté diced pumpkin and broccoli florets in olive oil, then fold into lentils.',
      'Season with fresh rosemary, Kosher salt, and cayenne pepper.',
    ],
  },
  {
    id: 'mid-snack-01',
    title: 'Beeren-Sommertraum (15:00–17:00 Uhr Snack)',
    titleEN: 'Summer Berry Delight (15:00–17:00 Snack)',
    mealName: 'Midday Berry Delight',
    description: 'Der perfekte Nachmittags-Snack nach Adano Ley: Frische Erdbeeren, Blaubeeren und Himbeeren zwischen 15:00 und 17:00 Uhr genießen.',
    descriptionEN: "The ultimate afternoon snack per Adano Ley: Enjoy fresh strawberries, blueberries, and raspberries between 15:00 and 17:00.",
    timeWindow: 'Midday',
    diet: 'Vegan',
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    difficulty: 'Einfach',
    cuisine: 'Solar Specialty',
    cuisineEN: 'Solar Specialty',
    isPreloaded: true,
    tags: ['Beeren', '15:00-17:00', 'Snack', 'Rohkost'],
    ingredients: [
      { name: 'Erdbeere (Strawberry)', nameEN: 'Strawberry', amount: '100g frische Erdbeeren', amountEN: '100g fresh strawberries' },
      { name: 'Blaubeere (Blueberry)', nameEN: 'Blueberry', amount: '50g Blaubeeren', amountEN: '50g blueberries' },
      { name: 'Himbeere (Raspberry)', nameEN: 'Raspberry', amount: '50g Himbeeren', amountEN: '50g raspberries' },
    ],
    instructions: [
      'Die Beeren vorsichtig abbrausen und trocken tupfen.',
      'Am besten zwischen 15:00 und 17:00 Uhr Solarzeit frisch genießen.',
    ],
    instructionsEN: [
      'Rinse berries gently and pat dry.',
      'Best enjoyed fresh strictly between 15:00 and 17:00 Solar Time.',
    ],
    tips: ['Beeren sind im Midday-Fenster (speziell 15-17 Uhr) am leichtesten zu verdauen.'],
    tipsEN: ['Berries are easiest to digest in the Midday window (specifically 15:00–17:00).'],
  },

  // ==========================================
  // EVENING RECIPES (18:00 - 24:00 Solarzeit) - UNDERGROUND & WATER & FUNGI & CAM
  // ==========================================
  {
    id: 'eve-01',
    title: 'Ofengeröstetes Wurzelgemüse mit Meersalz & Rosmarin',
    titleEN: 'Oven-Roasted Root Vegetables with Sea Salt & Rosemary',
    mealName: 'Roasted Root Harmony',
    description: 'Aromatisches Wurzelgemüse aus Süßkartoffeln, Karotten, Roter Bete und Pastinaken im Ofen geröstet, verfeinert mit Meersalz.',
    descriptionEN: 'Aromatic root vegetable blend of sweet potato, carrots, beetroot, and parsnip oven-roasted with genuine sea salt.',
    timeWindow: 'Evening',
    diet: 'Vegan',
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    servings: 2,
    difficulty: 'Einfach',
    cuisine: 'Ofengericht',
    cuisineEN: 'Oven Baked',
    isPreloaded: true,
    tags: ['Ofen', 'Ballaststoffe', 'Abendessen'],
    ingredients: [
      { name: 'Süßkartoffel (Sweet Potato)', nameEN: 'Sweet Potato', amount: '1 große Süßkartoffel', amountEN: '1 large sweet potato' },
      { name: 'Möhre / Karotte (Carrot)', nameEN: 'Carrot', amount: '2 Karotten', amountEN: '2 carrots' },
      { name: 'Rote Bete (Beetroot)', nameEN: 'Beetroot', amount: '1 Knolle Rote Bete', amountEN: '1 beetroot' },
      { name: 'Pastinake (Parsnip)', nameEN: 'Parsnip', amount: '1 Pastinake', amountEN: '1 parsnip' },
      { name: 'Olivenöl (Olive Oil)', nameEN: 'Olive Oil', amount: '2 EL', amountEN: '2 tbsp' },
      { name: 'Salz (Sea Salt)', nameEN: 'Sea Salt', amount: '1 TL Echtes Meersalz', amountEN: '1 tsp pure sea salt' },
      { name: 'Knoblauch (Garlic)', nameEN: 'Garlic', amount: '2 Zehen', amountEN: '2 cloves' },
    ],
    instructions: [
      'Den Backofen auf 200°C Ober-/Unterhitze vorheizen.',
      'Das Wurzelgemüse schälen und in Spalten oder Würfel schneiden.',
      'Mit Olivenöl, zerkleinertem Knoblauch und feinem Meersalz (Abend-Salz!) vermengen.',
      'Auf einem Backblech ca. 30 Minuten goldbraun rösten.',
    ],
    instructionsEN: [
      'Preheat oven to 200°C.',
      'Peel root vegetables and cut into wedges or cubes.',
      'Toss with olive oil, minced garlic, and fine sea salt (evening salt!).',
      'Roast on a baking tray for about 30 minutes until golden brown.',
    ],
    tips: ['Im Evening-Fenster stets Meersalz (Sea Salt) anstelle von Kosher Salt verwenden.'],
    tipsEN: ['Always use sea salt instead of Kosher salt during the Evening window.'],
  },
  {
    id: 'eve-02',
    title: 'Gegrilltes Lachsfilet auf Brunnenkresse & Pilzen',
    titleEN: 'Grilled Salmon Fillet on Watercress & Mushrooms',
    mealName: 'Ocean & Earth Salmon Plate',
    description: 'Frisch zubereitetes Lachsfilet auf gedünsteten Austernpilzen und Brunnenkresse, serviert mit duftendem Wildreis.',
    descriptionEN: 'Seared salmon fillet served over sautéed oyster mushrooms and fresh watercress with aromatic wild rice.',
    timeWindow: 'Evening',
    diet: 'Omnivore',
    prepTimeMinutes: 15,
    cookTimeMinutes: 18,
    servings: 2,
    difficulty: 'Mittel',
    cuisine: 'Gourmet',
    cuisineEN: 'Gourmet',
    isPreloaded: true,
    tags: ['Fisch', 'Omega3', 'Leicht'],
    ingredients: [
      { name: 'Lachs (Salmon)', nameEN: 'Salmon', amount: '2 Lachsfilets (je 150g)', amountEN: '2 salmon fillets (150g each)' },
      { name: 'Pilze (Mushrooms)', nameEN: 'Mushrooms', amount: '150g Austernpilze oder Champignons', amountEN: '150g oyster mushrooms or button mushrooms' },
      { name: 'Brunnenkresse (Watercress)', nameEN: 'Watercress', amount: '1 Handvoll Brunnenkresse', amountEN: '1 handful watercress' },
      { name: 'Wildreis (Wild Rice)', nameEN: 'Wild Rice', amount: '100g Adano 5:1 Reismischung', amountEN: '100g Adano 5:1 rice mix' },
      { name: 'Ghee (Klärbutter)', nameEN: 'Ghee (Clarified Butter)', amount: '1 EL', amountEN: '1 tbsp' },
      { name: 'Salz (Sea Salt)', nameEN: 'Sea Salt', amount: '1/2 TL Meersalz', amountEN: '1/2 tsp sea salt' },
    ],
    instructions: [
      'Die Reismischung (5 Teile brauner Reis auf 1 Teil Wildreis) gar kochen.',
      'Ghee in der Pfanne erhitzen und die Pilze sanft anbraten.',
      'Lachs auf der Hautseite 4-5 Minuten knusprig braten, wenden und weitere 2 Minuten ziehen lassen.',
      'Mit Meersalz würzen und auf dem Pilz-Brunnenkresse-Bett mit Reis anrichten.',
    ],
    instructionsEN: [
      'Cook the rice blend (5 parts brown rice to 1 part wild rice).',
      'Heat ghee in a pan and gently sauté mushrooms.',
      'Sear salmon skin-side down for 4-5 minutes, flip and cook 2 minutes more.',
      'Season with sea salt and serve on mushrooms and watercress alongside rice.',
    ],
  },
  {
    id: 'eve-de-01',
    title: 'Deutscher Kartoffel-Schmortopf mit Austernpilzen & Knoblauch',
    titleEN: 'German Potato & Oyster Mushroom Stew',
    mealName: 'German Potato & Oyster Mushroom Stew',
    description: 'Herzhafter deutscher Abendtopf aus vorwiegend festkochenden Kartoffeln, saftigen Möhren und gebratenen Austernpilzen, gewürzt mit echtem Meersalz.',
    descriptionEN: 'Hearty German evening stew of waxy potatoes, juicy carrots, and seared oyster mushrooms seasoned with pure sea salt.',
    timeWindow: 'Evening',
    diet: 'Vegetarian',
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 2,
    difficulty: 'Einfach',
    cuisine: 'Deutsch',
    cuisineEN: 'German',
    isPreloaded: true,
    tags: ['Deutsch', 'Abendessen', 'Kartoffel', 'Pilze'],
    ingredients: [
      { name: 'Kartoffel (Potato)', nameEN: 'Potato', amount: '400g vorwiegend festkochende Kartoffeln', amountEN: '400g waxy potatoes' },
      { name: 'Möhre / Karotte (Carrot)', nameEN: 'Carrot', amount: '2 große Karotten', amountEN: '2 large carrots' },
      { name: 'Pilze (Mushrooms)', nameEN: 'Mushrooms', amount: '200g Austernpilze', amountEN: '200g oyster mushrooms' },
      { name: 'Knoblauch (Garlic)', nameEN: 'Garlic', amount: '2 Zehen', amountEN: '2 cloves' },
      { name: 'Ghee (Klärbutter)', nameEN: 'Ghee (Clarified Butter)', amount: '2 EL', amountEN: '2 tbsp' },
      { name: 'Salz (Sea Salt)', nameEN: 'Sea Salt', amount: '1/2 TL Echtes Meersalz', amountEN: '1/2 tsp pure sea salt' },
      { name: 'Dreifach gefilterter Pfeffersud', nameEN: 'Filtered Pepper Extract', amount: '1 TL (oder Cayennepfeffer)', amountEN: '1 tsp (or cayenne pepper)' },
    ],
    instructions: [
      'Kartoffeln und Karotten schälen, in Würfel schneiden und in Salzwasser ca. 15 Minuten vorgehen.',
      'Ghee in einer tiefen Pfanne erhitzen, gehackten Knoblauch und zerkleinerte Austernpilze 6 Minuten goldbraun anbraten.',
      'Vorgekochte Kartoffeln und Karotten dazugeben und alles 5 Minuten durchschwenken.',
      'Mit feinem Meersalz und dreifach gefiltertem Pfeffersud (oder Cayennepfeffer) würzen.',
    ],
    instructionsEN: [
      'Peel and dice potatoes and carrots, parboiling in salted water for 15 minutes.',
      'Heat ghee in a skillet and brown garlic and oyster mushrooms for 6 minutes.',
      'Add parboiled potatoes and carrots, tossing together for 5 minutes.',
      'Season with sea salt and cayenne pepper before serving.',
    ],
  },
  {
    id: 'eve-it-01',
    title: 'Zuppa di Pesce alla Toscana (Toskanischer Meeresfrüchte-Eintopf)',
    titleEN: 'Zuppa di Pesce alla Toscana (Tuscan Seafood Stew)',
    mealName: 'Tuscan Seafood & Fennel Stew',
    description: 'Edler toskanischer Abend-Eintopf aus frischem Kabeljau, Garnelen, Fenchelknolle und Knoblauch, gegart in Olivenöl und verfeinert mit Meersalz.',
    descriptionEN: 'Fine Tuscan evening stew of fresh cod fillet, prawns, fennel bulb, and garlic poached in olive oil with sea salt.',
    timeWindow: 'Evening',
    diet: 'Omnivore',
    prepTimeMinutes: 20,
    cookTimeMinutes: 20,
    servings: 2,
    difficulty: 'Anspruchsvoll',
    cuisine: 'Italienisch',
    cuisineEN: 'Italian',
    isPreloaded: true,
    tags: ['Italienisch', 'Seafood', 'Abendessen', 'Gourmet'],
    ingredients: [
      { name: 'Kabeljau / Dorsch (Cod)', nameEN: 'Cod', amount: '250g frisches Kabeljaufilet', amountEN: '250g fresh cod fillet' },
      { name: 'Krabben / Garnelen (Shrimp/Crab)', nameEN: 'Prawns / Shrimp / Crab', amount: '150g Garnelen', amountEN: '150g prawns' },
      { name: 'Fenchelknolle (Fennel Bulb)', nameEN: 'Fennel Bulb', amount: '1 kleine Fenchelknolle, in Streifen', amountEN: '1 small fennel bulb, sliced' },
      { name: 'Knoblauch (Garlic)', nameEN: 'Garlic', amount: '2 Zehen', amountEN: '2 cloves' },
      { name: 'Olivenöl (Olive Oil)', nameEN: 'Olive Oil', amount: '3 EL', amountEN: '3 tbsp' },
      { name: 'Salz (Sea Salt)', nameEN: 'Sea Salt', amount: '1 TL Meersalz', amountEN: '1 tsp sea salt' },
      { name: 'Dreifach gefilterter Pfeffersud', nameEN: 'Filtered Pepper Extract', amount: '1 TL (oder Cayennepfeffer)', amountEN: '1 tsp (or cayenne pepper)' },
    ],
    instructions: [
      'Fenchelknolle und Knoblauch in Olivenöl in einem Topf 8 Minuten sanft andünsten.',
      'Etwas Wasser hinzugeben und aufkochen lassen.',
      'Kabeljau in Stücke schneiden und zusammen mit den Garnelen in den Fond geben, bei schwacher Hitze 8 Minuten gar ziehen lassen.',
      'Mit feinem Meersalz und dreifach gefiltertem Pfeffersud (oder Cayennepfeffer) verfeinern.',
    ],
    instructionsEN: [
      'Gentle sauté sliced fennel and garlic in olive oil for 8 minutes.',
      'Add a splash of water and bring to a simmer.',
      'Add chunked cod and prawns to the broth, poaching gently for 8 minutes.',
      'Finish with fine sea salt and cayenne pepper.',
    ],
  },
  {
    id: 'eve-fr-01',
    title: 'Bouillabaisse Provençale mit Knoblauch-Fenchel-Fond',
    titleEN: 'Provençal Bouillabaisse with Garlic-Fennel Broth',
    mealName: 'Provençal Bouillabaisse',
    description: 'Klassische südfranzösische Fischsuppe für den Abend: Dorsch und Miesmuscheln gekocht in einem duftenden Fond aus Wurzelgemüse, Knoblauch, Fenchel und Safran.',
    descriptionEN: 'Classic Southern French evening fish soup: Cod and mussels cooked in an aromatic broth of root vegetables, garlic, fennel, and saffron.',
    timeWindow: 'Evening',
    diet: 'Omnivore',
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    servings: 2,
    difficulty: 'Anspruchsvoll',
    cuisine: 'Französisch',
    cuisineEN: 'French',
    isPreloaded: true,
    tags: ['Französisch', 'Fisch', 'Abendessen', 'Gourmet'],
    ingredients: [
      { name: 'Kabeljau / Dorsch (Cod)', nameEN: 'Cod', amount: '200g Kabeljaufilet', amountEN: '200g cod fillet' },
      { name: 'Muscheln (Mussels/Clams)', nameEN: 'Mussels / Clams', amount: '200g frische Miesmuscheln', amountEN: '200g fresh mussels' },
      { name: 'Möhre / Karotte (Carrot)', nameEN: 'Carrot', amount: '1 Karotte', amountEN: '1 carrot' },
      { name: 'Fenchelknolle (Fennel Bulb)', nameEN: 'Fennel Bulb', amount: '1/2 Fenchelknolle', amountEN: '1/2 fennel bulb' },
      { name: 'Knoblauch (Garlic)', nameEN: 'Garlic', amount: '3 Zehen', amountEN: '3 cloves' },
      { name: 'Safran (Saffron)', nameEN: 'Saffron', amount: '1 Prise Safranfäden', amountEN: '1 pinch saffron threads' },
      { name: 'Olivenöl (Olive Oil)', nameEN: 'Olive Oil', amount: '2 EL', amountEN: '2 tbsp' },
      { name: 'Salz (Sea Salt)', nameEN: 'Sea Salt', amount: '1 TL Meersalz', amountEN: '1 tsp sea salt' },
      { name: 'Dreifach gefilterter Pfeffersud', nameEN: 'Filtered Pepper Extract', amount: '1 TL (oder Cayennepfeffer)', amountEN: '1 tsp (or cayenne)' },
    ],
    instructions: [
      'Karotte, Fenchel und Knoblauch fein würfeln und in Olivenöl anbraten.',
      'Mit Wasser auffüllen, Safranfäden dazugeben und 10 Minuten köcheln lassen.',
      'Fischstücke und vorbereitete Miesmuscheln hineingeben und 8 Minuten garen, bis sich die Muscheln öffnen.',
      'Mit Meersalz und dreifach gefiltertem Pfeffersud oder Cayennepfeffer abschmecken.',
    ],
    instructionsEN: [
      'Diced carrot, fennel, and garlic, sautéing in olive oil.',
      'Add water and saffron threads, simmering for 10 minutes.',
      'Add cod pieces and mussels, cooking for 8 minutes until mussels open.',
      'Season with sea salt and cayenne pepper before serving.',
    ],
  },
  {
    id: 'eve-es-01',
    title: 'Patatas Arrugadas mit gegrilltem Thunfisch & Knoblauch-Mojo',
    titleEN: 'Patatas Arrugadas with Grilled Tuna & Garlic Mojo',
    mealName: 'Spanish Canarian Tuna & Garlic Potatoes',
    description: 'Spanischer Kanaren-Klassiker zum Abendessen: In Meersalz gekochte Schalenkartoffeln serviert mit zartem Thunfischfilet und Knoblauch-Mojo.',
    descriptionEN: 'Canarian Spanish evening classic: Salt-crusted potatoes served with seared tuna fillet and garlic mojo.',
    timeWindow: 'Evening',
    diet: 'Omnivore',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 2,
    difficulty: 'Mittel',
    cuisine: 'Spanisch',
    cuisineEN: 'Spanish',
    isPreloaded: true,
    tags: ['Spanisch', 'Kartoffeln', 'Thunfisch', 'Meersalz'],
    ingredients: [
      { name: 'Thunfisch (Tuna)', nameEN: 'Tuna', amount: '2 Thunfischsteaks (je 150g)', amountEN: '2 tuna steaks (150g each)' },
      { name: 'Kartoffel (Potato)', nameEN: 'Potato', amount: '400g kleine Drillinge-Kartoffeln', amountEN: '400g small baby potatoes' },
      { name: 'Knoblauch (Garlic)', nameEN: 'Garlic', amount: '3 Zehen', amountEN: '3 cloves' },
      { name: 'Olivenöl (Olive Oil)', nameEN: 'Olive Oil', amount: '3 EL', amountEN: '3 tbsp' },
      { name: 'Salz (Sea Salt)', nameEN: 'Sea Salt', amount: '2 EL Echtes Meersalz (für den Salzmantel)', amountEN: '2 tbsp pure sea salt (for crust)' },
      { name: 'Cayennepfeffer (Cayenne Pepper)', nameEN: 'Cayenne Pepper', amount: '1/2 TL für die Mojo', amountEN: '1/2 tsp for mojo sauce' },
    ],
    instructions: [
      'Die ungeschälten Kartoffeln in wenig Wasser mit 2 EL Meersalz kochen, bis das Wasser verdampft und sich eine Salzkruste bildet.',
      'Knoblauch mit Olivenöl und Cayennepfeffer zu einer pikanten Knoblauch-Mojo pürieren.',
      'Thunfischsteaks in etwas Olivenöl von jeder Seite ca. 2 Minuten scharf anbraten (innen zart-rosa).',
      'Thunfisch mit Meersalz bestreuen und zusammen mit den Runzelkartoffeln und der Mojo servieren.',
    ],
    instructionsEN: [
      'Boil unpeeled baby potatoes in shallow water with 2 tbsp sea salt until water evaporates into a salt crust.',
      'Puree garlic with olive oil and cayenne pepper into a spicy mojo sauce.',
      'Sear tuna steaks in olive oil for 2 minutes per side until seared outside and pink inside.',
      'Season tuna with sea salt and serve alongside wrinkled potatoes and garlic mojo.',
    ],
  },
  {
    id: 'eve-03',
    title: 'Exotischer Ananas-Lachs mit Ingwer & Süßkartoffel-Stampf',
    titleEN: 'Exotic Pineapple Salmon with Ginger & Sweet Potato Mash',
    mealName: 'Exotic Evening Pineapple Salmon',
    description: 'Feinstes Lachsfilet mariniert in Ananassaft (CAM-Pflanze) und Ingwer, serviert auf feinem Süßkartoffel-Stampf.',
    descriptionEN: 'Prime salmon fillet marinated in pineapple juice (CAM plant) and ginger, served over smooth sweet potato mash.',
    timeWindow: 'Evening',
    diet: 'Omnivore',
    prepTimeMinutes: 15,
    cookTimeMinutes: 18,
    servings: 2,
    difficulty: 'Mittel',
    cuisine: 'Fusion / Exotisch',
    cuisineEN: 'Fusion / Exotic',
    isPreloaded: true,
    tags: ['Ananas', 'CAM', 'Lachs', 'Süßkartoffel', 'Gourmet'],
    ingredients: [
      { name: 'Lachs (Salmon)', nameEN: 'Salmon', amount: '2 Lachsfilets (je 150g)', amountEN: '2 salmon fillets (150g each)' },
      { name: 'Ananas (Pineapple)', nameEN: 'Pineapple', amount: '150g Ananaswürfel oder Ananassaft (CAM-Pflanze)', amountEN: '150g pineapple cubes or juice (CAM plant)' },
      { name: 'Süßkartoffel (Sweet Potato)', nameEN: 'Sweet Potato', amount: '300g Süßkartoffeln', amountEN: '300g sweet potatoes' },
      { name: 'Ingwer (Ginger)', nameEN: 'Ginger', amount: '1 TL frisch geriebener Ingwer', amountEN: '1 tsp fresh grated ginger' },
      { name: 'Olivenöl (Olive Oil)', nameEN: 'Olive Oil', amount: '2 EL', amountEN: '2 tbsp' },
      { name: 'Salz (Sea Salt)', nameEN: 'Sea Salt', amount: '1/2 TL Meersalz', amountEN: '1/2 tsp sea salt' },
      { name: 'Dreifach gefilterter Pfeffersud', nameEN: 'Filtered Pepper Extract', amount: '1 TL (oder Cayennepfeffer)', amountEN: '1 tsp (or cayenne)' },
    ],
    instructions: [
      'Süßkartoffeln schälen, würfeln, 15 Minuten weich kochen und mit etwas Olivenöl und Meersalz stampfen.',
      'Lachs in Olivenöl mit Ingwer anbraten.',
      'Ananaswürfel dazugeben und kurz karamellisieren lassen.',
      'Auf dem Süßkartoffelstampf anrichten und mit Meersalz und Pfeffersud/Cayennepfeffer abschmecken.',
    ],
    instructionsEN: [
      'Peel and cube sweet potatoes, boil for 15 minutes, and mash with olive oil and sea salt.',
      'Sear salmon in olive oil with fresh ginger.',
      'Add pineapple cubes and briefly caramelise.',
      'Serve over sweet potato mash and season with sea salt and cayenne pepper.',
    ],
    tips: ['Ananas ist eine CAM-Pflanze (Nachtstoffwechsel) und gehört laut Adano Ley strikt in das Evening-Fenster.'],
    tipsEN: ['Pineapple is a CAM plant (nocturnal metabolism) and belongs strictly in the Evening window per Adano Ley.'],
  },
  {
    id: 'eve-04',
    title: 'Herbstlicher Steinpilz-Kartoffel-Auflauf mit Knoblauch',
    titleEN: 'Autumnal Porcini & Potato Casserole with Garlic',
    mealName: 'Autumn Wild Mushroom & Potato Casserole',
    description: 'Herzhafter Abendauflauf aus knusprigen Kartoffelscheiben, edlen Steinpilzen, Eiern und Knoblauch, gebacken mit Ghee und Meersalz.',
    descriptionEN: 'Hearty evening bake of thinly sliced potatoes, wild porcini mushrooms, eggs, and garlic baked with ghee and sea salt.',
    timeWindow: 'Evening',
    diet: 'Vegetarian',
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    servings: 2,
    difficulty: 'Mittel',
    cuisine: 'Deutsch / Rustikal',
    cuisineEN: 'German / Rustic',
    isPreloaded: true,
    tags: ['Pilze', 'Kartoffeln', 'Eier', 'Vegetarisch'],
    ingredients: [
      { name: 'Kartoffel (Potato)', nameEN: 'Potato', amount: '400g Kartoffeln, dünn geschnitten', amountEN: '400g potatoes, thinly sliced' },
      { name: 'Pilze (Mushrooms)', nameEN: 'Mushrooms', amount: '200g frische Steinpilze oder Champignons', amountEN: '200g fresh porcini or button mushrooms' },
      { name: 'Ei (Egg)', nameEN: 'Egg', amount: '2 Eier (Abend-Verdauung)', amountEN: '2 eggs' },
      { name: 'Knoblauch (Garlic)', nameEN: 'Garlic', amount: '2 Zehen', amountEN: '2 cloves' },
      { name: 'Ghee (Klärbutter)', nameEN: 'Ghee (Clarified Butter)', amount: '2 EL', amountEN: '2 tbsp' },
      { name: 'Salz (Sea Salt)', nameEN: 'Sea Salt', amount: '1 TL Meersalz', amountEN: '1 tsp sea salt' },
      { name: 'Cayennepfeffer (Cayenne Pepper)', nameEN: 'Cayenne Pepper', amount: '1 Prise', amountEN: '1 pinch' },
    ],
    instructions: [
      'Kartoffelscheiben 8 Minuten vorgaren.',
      'Pilze und Knoblauch in Ghee anbraten.',
      'In einer Auflaufform Kartoffeln und Pilze schichten, mit verquirlten Eiern, Meersalz und Cayennepfeffer überschütten.',
      'Bei 190°C ca. 20 Minuten im Ofen stocken lassen.',
    ],
    instructionsEN: [
      'Parboil potato slices for 8 minutes.',
      'Sauté mushrooms and garlic in ghee.',
      'Layer potatoes and mushrooms in a baking dish, pour beaten eggs over top with sea salt and cayenne pepper.',
      'Bake at 190°C for 20 minutes until set.',
    ],
  },

  // ==========================================
  // DAWN TRANSITION RECIPES (11:30 - 12:30 Solarzeit)
  // ==========================================
  {
    id: 'dawn-01',
    title: 'Dawn Transition: Haferflocken mit Apfel & Zimt-Mandeln',
    titleEN: 'Dawn Transition: Apple & Cinnamon Almond Porridge',
    mealName: 'Sunrise Transition Porridge',
    description: 'Perfekte Überbrückung zwischen Morgen und Mittag (11:30–12:30 Uhr): Kräftige Haferflocken (Midday) kombiniert mit saftigem Apfel (Morning).',
    descriptionEN: 'Ideal transition between morning and midday (11:30–12:30): Hearty porridge oats (Midday) paired with crisp apple (Morning).',
    timeWindow: 'Dawn Transition',
    diet: 'Vegan',
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 1,
    difficulty: 'Einfach',
    cuisine: 'Frühstück / Übergang',
    cuisineEN: 'Breakfast / Transition',
    isPreloaded: true,
    tags: ['Dawn Transition', 'Porridge', 'Sättigend'],
    ingredients: [
      { name: 'Apfel (Apple)', nameEN: 'Apple', amount: '1 Apfel, gewürfelt (Morning)', amountEN: '1 apple, diced (Morning)' },
      { name: 'Hafer (Oats)', nameEN: 'Oats', amount: '60g Haferflocken (Midday)', amountEN: '60g porridge oats (Midday)' },
      { name: 'Mandeln (Almonds)', nameEN: 'Almonds', amount: '15g Mandeln (Morning)', amountEN: '15g almonds (Morning)' },
      { name: 'Ahornsirup (Maple Syrup)', nameEN: 'Maple Syrup', amount: '1 TL', amountEN: '1 tsp' },
      { name: 'Wasser / Pflanzendrink', nameEN: 'Water / Plant Milk', amount: '200ml', amountEN: '200ml' },
    ],
    instructions: [
      'Haferflocken in Wasser aufkochen und 5 Minuten simmer lassen.',
      'Den gewürfelten Apfel unterrühren.',
      'Mit gehackten Mandeln und Ahornsirup verfeinern.',
    ],
    instructionsEN: [
      'Bring oats and water to a boil, simmering for 5 minutes.',
      'Stir in the diced apple.',
      'Top with chopped almonds and maple syrup.',
    ],
    tips: ['Nur zwischen 11:30 und 12:30 Solarzeit verzehren, um die Fenster optimal zu verbinden.'],
    tipsEN: ['Consume only between 11:30 and 12:30 Solar Time to bridge the windows perfectly.'],
  },
  {
    id: 'dawn-02',
    title: 'Dawn Transition: Apfel-Buchweizen-Pancakes mit Ahornsirup',
    titleEN: 'Dawn Transition: Apple Buckwheat Pancakes with Maple Syrup',
    mealName: 'Apple Buckwheat Dawn Pancakes',
    description: 'Leckere Pfannkuchen aus Buchweizenmehl (Midday) mit gedünsteten Apfelscheiben (Morning) und Ahornsirup.',
    descriptionEN: 'Delicious buckwheat flour pancakes (Midday) topped with warm stewed apple slices (Morning) and maple syrup.',
    timeWindow: 'Dawn Transition',
    diet: 'Vegan',
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    servings: 2,
    difficulty: 'Einfach',
    cuisine: 'Übergang',
    cuisineEN: 'Transition',
    isPreloaded: true,
    tags: ['Dawn Transition', 'Pancakes', 'Apfel', 'Buchweizen'],
    ingredients: [
      { name: 'Buchweizen (Buckwheat)', nameEN: 'Buckwheat', amount: '100g Buchweizenmehl (Midday)', amountEN: '100g buckwheat flour (Midday)' },
      { name: 'Apfel (Apple)', nameEN: 'Apple', amount: '1 Apfel, dünn geschnitten (Morning)', amountEN: '1 apple, thinly sliced (Morning)' },
      { name: 'Ahornsirup (Maple Syrup)', nameEN: 'Maple Syrup', amount: '2 EL (Morning)', amountEN: '2 tbsp (Morning)' },
      { name: 'Kokosöl (Coconut Oil)', nameEN: 'Coconut Oil', amount: '1 EL zum Ausbacken (Morning)', amountEN: '1 tbsp for frying (Morning)' },
    ],
    instructions: [
      'Buchweizenmehl mit Wasser zu einem glatten Teig verrühren.',
      'Kokosöl in der Pfanne erhitzen und Pfannkuchen von beiden Seiten goldbraun ausbacken.',
      'Apfelscheiben kurz mit Ahornsirup dünsten und auf den Pfannkuchen servieren.',
    ],
    instructionsEN: [
      'Whisk buckwheat flour with water into a smooth batter.',
      'Heat coconut oil in a skillet and cook pancakes until golden on both sides.',
      'Stew apple slices briefly with maple syrup and serve over pancakes.',
    ],
  },

  // ==========================================
  // DUSK TRANSITION RECIPES (18:00 - 19:00 Solarzeit)
  // ==========================================
  {
    id: 'dusk-01',
    title: 'Dusk Transition: Brokkoli-Kartoffel-Pfanne mit Knoblauch',
    titleEN: 'Dusk Transition: Broccoli & Sweet Potato Sauté with Garlic',
    mealName: 'Dusk Transition Earth & Bush Saute',
    description: 'Ideale Kombination für die Abenddämmerung (18:00–19:00 Uhr): Oberirdischer Brokkoli (Midday) harmonisch vereint mit Süßkartoffeln (Evening).',
    descriptionEN: 'Ideal combination for dusk (18:00–19:00): Bush broccoli (Midday) harmoniously combined with sweet potato (Evening).',
    timeWindow: 'Dusk Transition',
    diet: 'Vegan',
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 2,
    difficulty: 'Einfach',
    cuisine: 'Übergang / Abend',
    cuisineEN: 'Transition / Evening',
    isPreloaded: true,
    tags: ['Dusk Transition', 'Gemüse', 'Herzhaft'],
    ingredients: [
      { name: 'Brokkoli (Broccoli)', nameEN: 'Broccoli', amount: '150g Brokkoli (Midday)', amountEN: '150g broccoli (Midday)' },
      { name: 'Süßkartoffel (Sweet Potato)', nameEN: 'Sweet Potato', amount: '1 große Süßkartoffel (Evening)', amountEN: '1 large sweet potato (Evening)' },
      { name: 'Knoblauch (Garlic)', nameEN: 'Garlic', amount: '1 Zehe (Evening)', amountEN: '1 clove (Evening)' },
      { name: 'Olivenöl (Olive Oil)', nameEN: 'Olive Oil', amount: '2 EL (AnyTime)', amountEN: '2 tbsp (AnyTime)' },
      { name: 'Salz (Sea Salt)', nameEN: 'Sea Salt', amount: '1/2 TL Meersalz (Evening)', amountEN: '1/2 tsp sea salt (Evening)' },
      { name: 'Cayennepfeffer (Cayenne Pepper)', nameEN: 'Cayenne Pepper', amount: '1 Prise', amountEN: '1 pinch' },
    ],
    instructions: [
      'Süßkartoffel würfeln und in Olivenöl ca. 12 Minuten braten.',
      'Brokkoliröschen und zerkleinerten Knoblauch dazugeben und weitere 8 Minuten dünsten.',
      'Mit Meersalz und Cayennepfeffer (oder dreifach gefiltertem Pfeffersud) abschmecken.',
    ],
    instructionsEN: [
      'Dice sweet potato and sauté in olive oil for 12 minutes.',
      'Add broccoli florets and minced garlic, cooking for another 8 minutes.',
      'Season with sea salt and cayenne pepper before serving.',
    ],
    tips: ['Ideal für den Übergang von der Mittags- zur Abendenergie.'],
    tipsEN: ['Ideal for transitioning from midday to evening energy.'],
  },
  {
    id: 'dusk-02',
    title: 'Dusk Transition: Gekochte Kochbanane auf Kürbis-Karotten-Püree',
    titleEN: 'Dusk Transition: Cooked Plantain over Pumpkin & Carrot Mash',
    mealName: 'Plantain & Pumpkin Dusk Mash',
    description: 'Perfekte Dämmerungsmahlzeit: Gekochte Kochbanane (Morning/Evening Spezialnahrung) auf geschmeidigem Kürbis- (Midday) und Karotten-Püree (Evening).',
    descriptionEN: 'Perfect dusk meal: Cooked plantain slices served over smooth pumpkin (Midday) and carrot mash (Evening).',
    timeWindow: 'Dusk Transition',
    diet: 'Vegan',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 2,
    difficulty: 'Einfach',
    cuisine: 'Übergang',
    cuisineEN: 'Transition',
    isPreloaded: true,
    tags: ['Dusk Transition', 'Kochbanane', 'Kürbis', 'Möhre'],
    ingredients: [
      { name: 'Kochbanane (Plantain)', nameEN: 'Plantain (Cooking Banana)', amount: '1 gelbe Kochbanane, in Scheiben (Morning/Evening)', amountEN: '1 yellow plantain, sliced (Morning/Evening)' },
      { name: 'Kürbis (Pumpkin)', nameEN: 'Pumpkin', amount: '200g Hokkaido-Kürbis (Midday)', amountEN: '200g Hokkaido pumpkin (Midday)' },
      { name: 'Möhre / Karotte (Carrot)', nameEN: 'Carrot', amount: '2 Karotten (Evening)', amountEN: '2 carrots (Evening)' },
      { name: 'Olivenöl (Olive Oil)', nameEN: 'Olive Oil', amount: '2 EL', amountEN: '2 tbsp' },
      { name: 'Salz (Sea Salt)', nameEN: 'Sea Salt', amount: '1/2 TL Meersalz (Evening)', amountEN: '1/2 tsp sea salt (Evening)' },
    ],
    instructions: [
      'Kochbanane in scheiben Schneiden und in leicht gesalzenem Wasser 15 Minuten weich kochen.',
      'Kürbis und Karotten würfeln, 15 Minuten dämpfen und mit Olivenöl und Meersalz pürieren.',
      'Kochbananenscheiben auf dem warmen Püree servieren.',
    ],
    instructionsEN: [
      'Slice plantain and boil in lightly salted water for 15 minutes until tender.',
      'Steam diced pumpkin and carrots for 15 minutes, then mash with olive oil and sea salt.',
      'Serve plantain slices over the warm pumpkin-carrot mash.',
    ],
  },
];
